### ISSUE TITLE
Height on Android does not get updated

### ISSUE THREAD

**Issue by ralphdas** [rusfearuth/react-native-auto-grow-textinput#3]
Since the callback argument only gets called once on Android the height never gets updated. I changed it to onChange in the following PR: https://github.com/rusfearuth/react-native-auto-grow-textinput/pull/2

**Comment by rusfearuth** [comment]
@ralphdas I've taken your PR and updated it. Now it works with both platforms fine.

**Comment by ralphdas** [comment]
Great to hear!
